### ISSUE TITLE
What is the F123Tips?

### ISSUE THREAD

**Issue by alexandre-mbm** [F123/F123Tips#1]
Why it is empty?

**Comment by ghost** [comment]
It's possible that this repository can be deleted. The tips are
actually hosted on the server with the help and menus. That said, this
repository could be kept in case having it makes it easier to report
problems with the tips.

**Comment by alexandre-mbm** [comment]
Where exactly the tips are hosted today?

**Comment by ghost** [comment]
THe tips are hosted along with the help and menu files as part of
f123box. The complete URL is 
http://f123.org/f123box
but there is no index file there, so the server blocks the page. At
some point, I would like to move all the f123box files into a git
repository, as this would make things much easier to modify, but the
build system is getting the highest priority at the moment.

**Comment by alexandre-mbm** [comment]
Go to #2
